version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: sql_container
    environment:
      MYSQL_ROOT_PASSWORD: Deviljin1
      MYSQL_DATABASE: Login
    ports:
      - "8080:3306" 
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - my-network

  backend:
    image: task0-backend # already built backend image. That's why only given the name of image here.
    container_name: task0-backend
    depends_on:
      - db
    ports:
      - "4000:4000" 
    networks:
      - my-network

  frontend:
    image: task0-frontend # already built backend image. That's why only given the name of image here.
    container_name: task0-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
